### ISSUE TITLE
Do not replace " , " to " . "

### ISSUE THREAD

**Issue by shaddam** [ciromattia/jquery.counterup#11]
They  are provide this code for extra parameters , But formatter not working. 
Just here was missing formatter callback function "  );  "

$('.counter').counterUp({
    delay: 10,
    time: 1000,
    offset: 70,
    beginAt: 100,
    formatter: function (n) {
      return n.replace(/,/g, '.');
    });
});

This is working code : 
jQuery('.counter').counterUp({
    delay: 10,
    time: 1000,
    formatter: function (n) {
     return n.replace(/,/g, '.');
    }
});

**Comment by ciromattia** [comment]
Updated README, thanks!
